//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceYear { get; set; }
        public string InvoiceMonth { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceCompany { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> ConfirmedByAllUser { get; set; }
        public string Invoice { get; set; }
        public string TaxNumber { get; set; }
        public string Unite { get; set; }
        public string Branch { get; set; }
        public string TotalStr { get; set; }
    }
}
