//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_User
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<bool> Confirm { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string UserName { get; set; }
        public string DepartmanName { get; set; }
    }
}
