//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FaturaEntities : DbContext
    {
        public FaturaEntities()
            : base("name=FaturaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<ConfirmDetails> ConfirmDetails { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Invoice_User> Invoice_User { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
