//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public byte Id { get; set; }
        public string Name { get; set; }
        public Nullable<byte> DepartmentId { get; set; }
        public string Department { get; set; }
        public Nullable<int> Type { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public string Branch { get; set; }
    }
}
